### ISSUE TITLE
Feat: Implement the Solution page

### ISSUE THREAD

**Issue by samuelroland** [plx-pdg/plx#74]
- Add a `solution.rs` file
- Adapt the core to get the content of each exo.solution files to not read it from the UI. @AndreCostaaa maybe can help with this ?
- Show the filename of each exo (see example in `train::render_exo`) and the content right after it.
- Support syntax highlighting, maybe see what [bat](https://github.com/sharkdp/bat) did or [crate syntect](https://crates.io/crates/syntect) or something better idk.

**Comment by AndreCostaaa** [comment]
Closed by #100
